name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull docker images
      run: docker build -t back  . 
      
    - name: Run docker images
      run: docker run --rm --name back -p 3000:3000 -d back

    - name: Exec cucumber
      run: docker exec -it back rake cucumber:all
